import { ServiceCategory } from "./services";

export const demoServiceCategories: ServiceCategory[] = [
  {
    id: "demo-hair",
    name: "Hair",
    slug: "hair",
    description: "Expert hair styling, cuts, colouring and advanced treatments using premium salon products.",
    icon: "Scissors",
    image: "",
    enabled: true,
    sortOrder: 1,
    isDemo: true,
    services: [
      {
        id: "demo-hair-1",
        name: "Hair Spa",
        slug: "hair-spa",
        shortDescription: "A relaxing hair and scalp treatment designed to refresh the hair and provide a nourishing salon experience.",
        description: "Experience ultimate relaxation with our deep nourishing Hair Spa. This treatment involves a gentle massage to stimulate the scalp, applying nutrient-rich creams to restore moisture and shine, followed by a warm steam treatment to lock in hydration. Demo description for UI testing.",
        price: "₹799",
        priceNote: "Starting from",
        duration: "60 minutes",
        image: "",
        benefits: ["Refreshes hair texture", "Deeply nourishes scalp", "Relaxing salon experience"],
        suitableFor: ["Dry hair", "Frizzy hair", "Scalp tension"],
        preparation: ["No special preparation required. Come with unwashed hair if preferred."],
        aftercare: ["Avoid washing hair for 24 hours.", "Use mild sulfate-free shampoo."],
        faqs: [
          { question: "How long does the effect last?", answer: "Usually 2-3 weeks depending on your hair care routine." }
        ],
        enabled: true,
        sortOrder: 1,
        isDemo: true,
      },
      {
        id: "demo-hair-2",
        name: "Keratin Treatment",
        slug: "keratin-treatment",
        shortDescription: "Demo description for UI testing of the service detail experience.",
        description: "A professional smoothing treatment that infuses keratin deep into the hair cuticle, eliminating frizz and curl for a silky, smooth finish. Demo description for UI testing of the service detail experience.",
        price: "₹3,999",
        priceNote: "Starting from",
        duration: "120 minutes",
        image: "",
        benefits: ["Smoother-looking hair", "Easier styling", "Salon finishing experience", "Frizz reduction"],
        suitableFor: ["Curly hair", "Frizzy hair", "Unmanageable hair"],
        preparation: ["Demo preparation information for UI testing."],
        aftercare: ["Demo aftercare information for UI testing.", "Use only keratin-safe shampoo."],
        faqs: [
          { question: "Is this a permanent straightening?", answer: "No, it is a semi-permanent smoothing treatment." }
        ],
        enabled: true,
        sortOrder: 2,
        isDemo: true,
      },
      {
        id: "demo-hair-3",
        name: "Haircut & Styling",
        slug: "haircut",
        shortDescription: "Professional haircut customized to your face shape and personal style.",
        description: "Our expert stylists will consult with you to determine the best cut for your face shape, lifestyle, and hair texture.",
        price: "₹999",
        priceNote: "",
        duration: "45 minutes",
        image: "",
        benefits: ["Fresh look", "Removes split ends", "Easier daily styling"],
        suitableFor: ["All hair types"],
        preparation: [],
        aftercare: [],
        faqs: [],
        enabled: true,
        sortOrder: 3,
        isDemo: true,
      },
      {
        id: "demo-hair-4",
        name: "Global Hair Colour",
        slug: "hair-colour",
        shortDescription: "Premium hair coloring services using high-quality professional products.",
        description: "Transform your look with our professional coloring service. Includes consultation, application, and finishing style.",
        price: "₹2,499",
        priceNote: "Starting from",
        duration: "150 minutes",
        image: "",
        benefits: ["Vibrant color", "Grey coverage", "Glossy finish"],
        suitableFor: ["All hair types"],
        preparation: [],
        aftercare: ["Use color-protect shampoo"],
        faqs: [],
        enabled: true,
        sortOrder: 4,
        isDemo: true,
      },
    ],
  },
  {
    id: "demo-skin",
    name: "Skin & Facials",
    slug: "skin",
    description: "Advanced skincare & facial treatments for a radiant, healthy glow.",
    icon: "Sparkles",
    image: "",
    enabled: true,
    sortOrder: 2,
    isDemo: true,
    services: [
      {
        id: "demo-skin-1",
        name: "Glow Facial",
        slug: "glow-facial",
        shortDescription: "A salon facial experience focused on cleansing, hydration and a refreshed appearance.",
        description: "This signature facial uses premium botanical extracts to brighten dull skin. It includes deep cleansing, gentle exfoliation, a relaxing massage, and a specialized glow-boosting mask.",
        price: "₹1,299",
        priceNote: "",
        duration: "75 minutes",
        image: "",
        benefits: ["Instant brightness", "Deep hydration", "Relaxation"],
        suitableFor: ["Dull skin", "Tired skin", "Special occasions"],
        preparation: ["Avoid harsh exfoliants 2 days prior"],
        aftercare: ["Apply sunscreen", "Avoid heavy makeup for 12 hours"],
        faqs: [],
        enabled: true,
        sortOrder: 1,
        isDemo: true,
      },
      {
        id: "demo-skin-2",
        name: "Deep Cleansing Facial",
        slug: "deep-cleansing",
        shortDescription: "Purifying treatment to unclog pores and clear the complexion.",
        description: "A thorough cleansing facial designed to extract impurities and balance oil production.",
        price: "₹1,499",
        priceNote: "",
        duration: "60 minutes",
        image: "",
        benefits: ["Clearer pores", "Reduced oiliness"],
        suitableFor: ["Oily skin", "Congested skin"],
        preparation: [],
        aftercare: [],
        faqs: [],
        enabled: true,
        sortOrder: 2,
        isDemo: true,
      },
      {
        id: "demo-skin-3",
        name: "De-Tan Treatment",
        slug: "detan",
        shortDescription: "Effective treatment to remove sun tan and even out skin tone.",
        description: "A specialized pack and massage that gently removes superficial tanning and restores natural skin tone.",
        price: "₹699",
        priceNote: "",
        duration: "30 minutes",
        image: "",
        benefits: ["Removes sun tan", "Evens skin tone"],
        suitableFor: ["Sun-exposed skin"],
        preparation: [],
        aftercare: [],
        faqs: [],
        enabled: true,
        sortOrder: 3,
        isDemo: true,
      },
    ],
  },
  {
    id: "demo-bridal",
    name: "Bridal",
    slug: "bridal",
    description: "Complete bridal beauty services ensuring you look perfect on your special day.",
    icon: "Crown",
    image: "",
    enabled: true,
    sortOrder: 3,
    isDemo: true,
    services: [
      {
        id: "demo-bridal-1",
        name: "Bridal Makeup",
        slug: "bridal-makeup",
        shortDescription: "A complete bridal beauty experience designed for wedding-day styling.",
        description: "Our signature bridal service includes HD or Airbrush makeup, elaborate hairstyling, dupatta/saree draping, and premium accessory placement. Demo description for UI testing.",
        price: "₹12,999",
        priceNote: "Starting from",
        duration: "180 minutes",
        image: "",
        benefits: ["Long-lasting finish", "Flawless in photography", "Complete styling"],
        suitableFor: ["Brides"],
        preparation: ["Book a consultation 1 month prior", "Complete facials 1 week before"],
        aftercare: ["Professional makeup removal required"],
        faqs: [],
        enabled: true,
        sortOrder: 1,
        isDemo: true,
      },
      {
        id: "demo-bridal-2",
        name: "Pre-Bridal Package",
        slug: "pre-bridal",
        shortDescription: "Comprehensive grooming package before the big day.",
        description: "Includes body polishing, advanced facials, hair spa, and complete waxing.",
        price: "₹5,999",
        priceNote: "Package",
        duration: "150 minutes",
        image: "",
        benefits: ["Head-to-toe grooming", "Glowing skin"],
        suitableFor: ["Brides-to-be"],
        preparation: [],
        aftercare: [],
        faqs: [],
        enabled: true,
        sortOrder: 2,
        isDemo: true,
      },
    ],
  },
  {
    id: "demo-makeup",
    name: "Makeup",
    slug: "makeup",
    description: "Professional makeup for every occasion, from subtle to glamorous.",
    icon: "Palette",
    image: "",
    enabled: true,
    sortOrder: 4,
    isDemo: true,
    services: [
      {
        id: "demo-makeup-1",
        name: "Party Makeup",
        slug: "party-makeup",
        shortDescription: "Professional makeup styling for celebrations and special occasions.",
        description: "A glamorous makeup look tailored to your outfit and the event. Includes basic hair styling.",
        price: "₹2,499",
        priceNote: "",
        duration: "90 minutes",
        image: "",
        benefits: ["Flawless look", "Event-appropriate styling"],
        suitableFor: ["Party guests", "Bridesmaids"],
        preparation: ["Have a clean face"],
        aftercare: [],
        faqs: [],
        enabled: true,
        sortOrder: 1,
        isDemo: true,
      },
      {
        id: "demo-makeup-2",
        name: "HD Makeup",
        slug: "hd-makeup",
        shortDescription: "High-definition makeup perfect for photography and videography.",
        description: "Using specialized HD products that diffuse light and create a flawless, natural finish on camera.",
        price: "₹3,999",
        priceNote: "",
        duration: "90 minutes",
        image: "",
        benefits: ["Camera-ready", "Lightweight feel"],
        suitableFor: ["Photoshoots", "Special events"],
        preparation: [],
        aftercare: [],
        faqs: [],
        enabled: true,
        sortOrder: 2,
        isDemo: true,
      },
    ],
  },
  {
    id: "demo-nails",
    name: "Nails",
    slug: "nails",
    description: "Manicure, pedicure & beautiful nail art.",
    icon: "Hand",
    image: "",
    enabled: true,
    sortOrder: 5,
    isDemo: true,
    services: [
      {
        id: "demo-nails-1",
        name: "Classic Manicure",
        slug: "classic-manicure",
        shortDescription: "A complete nail grooming experience including shaping, care and finishing.",
        description: "Includes nail shaping, cuticle care, a relaxing hand massage, and application of a polish of your choice.",
        price: "₹699",
        priceNote: "",
        duration: "45 minutes",
        image: "",
        benefits: ["Clean nails", "Soft hands", "Polished look"],
        suitableFor: ["Everyone"],
        preparation: [],
        aftercare: ["Allow polish to dry completely"],
        faqs: [],
        enabled: true,
        sortOrder: 1,
        isDemo: true,
      },
      {
        id: "demo-nails-2",
        name: "Gel Polish",
        slug: "gel-polish",
        shortDescription: "Long-lasting gel nail polish application.",
        description: "High-gloss, chip-resistant gel polish cured under LED light.",
        price: "₹999",
        priceNote: "",
        duration: "60 minutes",
        image: "",
        benefits: ["Chip-resistant", "Lasts up to 3 weeks"],
        suitableFor: ["Long-lasting wear"],
        preparation: [],
        aftercare: [],
        faqs: [],
        enabled: true,
        sortOrder: 2,
        isDemo: true,
      },
    ],
  },
  {
    id: "demo-spa",
    name: "Spa & Wellness",
    slug: "spa",
    description: "Relaxing spa treatments to rejuvenate your mind and body.",
    icon: "Flower2",
    image: "",
    enabled: true,
    sortOrder: 6,
    isDemo: true,
    services: [
      {
        id: "demo-spa-1",
        name: "Head Massage",
        slug: "head-massage",
        shortDescription: "A relaxing scalp and head massage experience.",
        description: "Relieve stress and tension with our signature head massage using warm, aromatic oils.",
        price: "₹599",
        priceNote: "",
        duration: "30 minutes",
        image: "",
        benefits: ["Stress relief", "Improves circulation"],
        suitableFor: ["Stress relief"],
        preparation: [],
        aftercare: [],
        faqs: [],
        enabled: true,
        sortOrder: 1,
        isDemo: true,
      },
      {
        id: "demo-spa-2",
        name: "Body Spa",
        slug: "body-spa",
        shortDescription: "Full body relaxation massage.",
        description: "A complete body therapy designed to soothe muscles and calm the mind.",
        price: "₹1,999",
        priceNote: "",
        duration: "60 minutes",
        image: "",
        benefits: ["Muscle relaxation", "Mental calm"],
        suitableFor: ["Fatigue", "Stress"],
        preparation: [],
        aftercare: ["Drink plenty of water"],
        faqs: [],
        enabled: true,
        sortOrder: 2,
        isDemo: true,
      },
    ],
  },
];
